---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ubuntu
inputs:
  - name: deploy-discourse.git
  - name: discourse.github-release
outputs:
  - name: prometheus-boshrelease.src
run:
  path: deploy-prometheus.git/ci/scripts/extract-release-src.sh
params:
  INPUT_FILE: discourse.github-release/source.tar.gz
  OUTPUT_DIR: discourse.src
