platform: linux
image_resource:
  type: docker-image
  source: {repository: ubuntu}
inputs:
- name: deploy-discourse.git
- name: discourse.src
run:
  path: deploy-discourse.git/ci/scripts/modify.sh
  args: []
outputs:
- name: discourse.src-modified
params:
  INPUT_DIR: discourse.src
  OUTPUT_DIR: discourse.src-modified
