groups: []
resources:
- name: discourse.git
  type: git
  source:
    tag_filter: v*
    uri: https://github.com/discourse/discourse.git
- name: deploy-discourse.git
  type: git
  source:
    branch: master
    uri: https://github.com/govau/deploy-discourse.git
- name: slack
  type: slack-notification
  source:
    url: ((concourse-slack-webhook-url))
- name: d-cf
  # type: govau-cf
  type: cf
  source:
    api: https://api.system.d.cld.gov.au
    organization: cloud
    password: ((d-password))
    space: brendan
    username: ci-dta-discourse
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
# - name: govau-cf
#   type: docker-image
#   source:
#     repository: govau/cf-resource
#     tag: venapp
jobs:
- name: fetch
  plan:
  - aggregate:
    - get: discourse.git
      trigger: true
    - get: deploy-discourse.git
      trigger: true
  on_failure:
    put: slack
    params:
      text: |
        :x: $ATC_EXTERNAL_URL - $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: $ATC_EXTERNAL_URL - Successfully fetched new discourse - $TEXT_FILE_CONTENT
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      text_file: discourse.git/tag
- name: test-it
  serial_groups:
  - d-cld
  plan:
  - do:
    - aggregate:
      - get: discourse.git
        passed:
        - fetch
        trigger: true
      - get: deploy-discourse.git
        passed:
        - fetch
        trigger: true
    - task: modify
      file: deploy-discourse.git/ci/tasks/modify.yml
    - put: d-cf
      params:
        current_app_name: discourse
        manifest: discourse.git-modified/manifest-discourse.yml
        show_app_log: true
