groups: []
resources:
- name: discourse.git
  type: git
  source:
    tag_filter: v*
    uri: https://github.com/discourse/discourse.git
- name: deploy-discourse.git
  type: git
  source:
    branch: master
    uri: https://github.com/govau/deploy-discourse.git
- name: slack
  type: slack-notification
  source:
    url: ((concourse-slack-webhook-url))
- name: y-cf-staging
  type: cf
  source:
    api: https://api.system.y.cld.gov.au
    organization: dta
    password: ((y-password))
    space: discourse-staging
    username: ci-dta-discourse
- name: y-cf
  type: cf
  source:
    api: https://api.system.y.cld.gov.au
    organization: dta
    password: ((y-password))
    space: discourse
    username: ci-dta-discourse
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
jobs:
- name: fetch
  plan:
  - aggregate:
    - get: discourse.git
      trigger: true
    - get: deploy-discourse.git
      trigger: true
  on_failure:
    put: slack
    params:
      text: |
        :x: $ATC_EXTERNAL_URL - $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: $ATC_EXTERNAL_URL - Successfully fetched new discourse - $TEXT_FILE_CONTENT
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      text_file: discourse.git/tag
- name: deploy-it-y-staging
  serial_groups:
  - y-cld-staging
  plan:
  - do:
    - aggregate:
      - get: discourse.git
        passed:
        - fetch
        trigger: true
      - get: deploy-discourse.git
        passed:
        - fetch
        trigger: true
    - task: modify
      file: deploy-discourse.git/ci/tasks/modify.yml
      params:
        ROUTE: ((staging-route))
    - put: y-cld staging discourse
      resource: y-cf-staging
      params:
        current_app_name: discourse
        manifest: discourse.git-modified/manifest-discourse.yml
    - put: y-cld staging sidekiq
      resource: y-cf-staging
      params:
        current_app_name: sidekiq
        manifest: discourse.git-modified/manifest-sidekiq.yml
  on_failure:
    put: slack
    params:
      text: |
        :x: $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: $BUILD_JOB_NAME SUCCESS
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      text_file: discourse.git/tag
- name: deploy-it-y
  serial_groups:
  - y-cld-prod
  plan:
  - do:
    - aggregate:
      - get: discourse.git
        passed:
        - deploy-it-y-staging
      - get: deploy-discourse.git
        passed:
        - deploy-it-y-staging
    - task: modify
      file: deploy-discourse.git/ci/tasks/modify.yml
      params:
        ROUTE: ((prod-route))
    - put: y-cld prod discourse
      resource: y-cf
      params:
        current_app_name: discourse
        manifest: discourse.git-modified/manifest-discourse.yml
    - put: y-cld prod sidekiq
      resource: y-cf
      params:
        current_app_name: sidekiq
        manifest: discourse.git-modified/manifest-sidekiq.yml
  on_failure:
    put: slack
    params:
      text: |
        :x: $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: $BUILD_JOB_NAME SUCCESS
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      text_file: discourse.git/tag
