groups: []
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
- name: govau-cf
  type: docker-image
  source:
    repository: govau/cf-resource
    tag: venapp
resources:
- name: discourse.github-release
  type: github-release
  source:
    access_token: ((github-read-public-repos-token))
    owner: discourse
    repository: discourse
- name: deploy-discourse.git
  type: git
  source:
    branch: master
    uri: https://github.com/govau/deploy-discourse.git
- name: slack
  type: slack-notification
  source:
    url: ((concourse-slack-webhook-url))
- name: d-cf
  type: govau-cf
  source:
    api: https://api.system.d.cld.gov.au
    username: ci-dta-discourse
    password: ((d-password))
    organization: cloud
    space: brendan

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
- name: bosh2-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
    tag: v2.6.1
jobs:
- name: fetch
  plan:
  - aggregate:
    - get: discourse.github-release
      params:
        include_source_tarball: true
      # trigger: true
    - get: deploy-discourse.git
      # trigger: true
  on_failure:
    put: slack
    params:
      text: |
        :x: $ATC_EXTERNAL_URL - $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: $ATC_EXTERNAL_URL - Successfully fetched new discourse github release - $TEXT_FILE_CONTENT
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      text_file: discourse.github-release/tag
- name: test-it
  serial_groups: [d-cld]
  plan:
  - do:
    - aggregate:
      - get: discourse.github-release
        params:
          include_source_tarball: true
        passed: [fetch]
      - get: deploy-discourse.git
        passed: [fetch]
    - task: extract-release-src
      file: deploy-discourse.git/ci/tasks/extract-release-src.yml
    - task: modify
      file: deploy-discourse.git/ci/tasks/modify.yml
    - put: d-cf
      params:
        manifest: discourse.src-modified/manifest-discourse.yml
        path: discourse.src-modified
        current_app_name: discourse
        show_app_log: true
